baseURL: "https://awainverse.github.io/hugo-pascal" 
title: Aaron Anderson
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags
    coauthor: coauthors
    paper_type: paper_types

menu:
    main:
        - name: About Me
          url: about_me/
          weight: 1
        - name: Research
          url: research/
          weight: 2
        - name: Teaching
          url: teaching/
          weight: 3
        - name: Talks
          url: talks/
          weight: 4

params:
    description: "I am a Hans Rademacher Instructor at UPenn, researching model theory."
    author: Aaron Anderson
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["about_me","research","teaching","talks"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Aaron Anderson
          subtitle: I am a Hans Rademacher Instructor (postdoc) at UPenn, working with <a href ="https://www.sas.upenn.edu/~htowsner/">Henry Towsner</a>. I'm interested in model theory as it relates to combinatorics and other fields. I did my Ph.D. at UCLA, working with <a href="https://chernikov.umd.edu">Artem Chernikov</a>.
          imageUrl: "portrait.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: About Me
              url: about_me/
            - name: Research
              url: research/
            - name: Teaching
              url: teaching/
            - name: Talks
              url: talks/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:awanders@sas.upenn.edu
        - name: Office Hours
          url: officehours/
        - name: ORCID
          url: https://orcid.org/0000-0003-1092-0188
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=IMoj89EAAAAJ
        - name: GitHub
          url: https://github.com/awainverse

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Aaron Anderson"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2